version: '3.8'

services:
  monitoring-backend:
    build: .
    container_name: monitoring-backend
    ports:
      - "8000:8000"
    volumes:
      # Mount logs directory for persistence
      - ./logs:/app/logs
      # Optional: mount the entire backend directory for development
      # - .:/app
    environment:
      - PYTHONPATH=/app
      - INGEST_SECRET=your-shared-secret-key-here
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge