"""Update docker_events table schema - increase type column size and change action to text

Revision ID: abc123def456
Revises: fcc606ae3910
Create Date: 2025-01-21 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc123def456'
down_revision = 'fcc606ae3910'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Alter docker_events table columns to prevent truncation errors
    op.alter_column('docker_events', 'type',
                    existing_type=sa.String(length=50),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    
    op.alter_column('docker_events', 'action',
                    existing_type=sa.String(length=50),
                    type_=sa.Text(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert docker_events table columns back to original sizes
    op.alter_column('docker_events', 'action',
                    existing_type=sa.Text(),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    
    op.alter_column('docker_events', 'type',
                    existing_type=sa.String(length=255),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    # ### end Alembic commands ###